*** Variables ***
${ADD_TO_CART_BUTTON}    css:a.add_to_cart_button

${COUPON_TOGGLE}                 css:div.wc-block-components-panel__button[role='button']
${COUPON_FIELD}                  css:input#wc-block-components-totals-coupon__input-coupon
${APPLY_COUPON_BUTTON}           css:button.wc-block-components-totals-coupon__button
${CART_PAGE_MESSAGE}             css:div.wc-block-components-notice-banner__content
${PROCEED_TO_CHECKOUT_BTN}       xpath://span[text()='Proceed to Checkout']/..
